lab.devices.url=http://192.168.0.50/api/nm-clinic-api/api/v0/lab/get/integrated/devices

lab.devices.retryDelayMs=5000
lab.devices.dh76.resultsUrl=
lab.devices.c311.orderUrl=http://192.168.0.50/api/nm-clinic-api/api/v0/lab/cobas/c311/order/data
lab.devices.abl90.resultsUrl=
lab.devices.resultsUrl=http://192.168.0.50/api/nm-clinic-api/api/v0/lab/incoming/results
lab.ui.mock=false
lab.devices.mockOnError=false
lab.ui.mock.deviceCount=3
lab.ui.mock.intervalMs=1000
lab.logs.maxLines=500
